### ISSUE TITLE
How to add tests ? 

### ISSUE THREAD

**Issue by renetik** [ferhanakkan/AppCircleSampleProject#1]
I mean test that import UIKit.. 

I see tests in  cocoapods example project but .. This is the only way ? It would be cool if I have on development local package and I can run my tests that are included in workspace so when I do refactoring everything gets refactored.. I dream big I suppose...

**Comment by ferhanakkan** [comment]
Can you give an example for a scenario where you want to add a test? @rene-dohan

**Comment by renetik** [comment]
Simple scenario is that I now released som libraries https://github.com/renetik/renetik-ios-layout 
and other to release for public is https://github.com/renetik/renetik-ios-event , now I am adding test there and it looks like it works just you have to use special args to run it from command line:

xcodebuild -scheme RenetikEvent test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11'

I was asking because you omitted tests but I need both demo project for something and command line executable tests too...
